spring.application.name=student-management
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/student_management_db

# CORS
spring.web.cors.allowed-origins=http://localhost:5173

server.forward-headers-strategy=framework